[package]
name = "qr_native"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Fast, customizable QR rendering for Node.js"
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
lto = "thin"

[dependencies]
napi = { version = "3.13.0", default-features = false, features = ["napi10"] }
napi-derive = "3.6.9"
zlib-rs = { version = "0.6.8", default-features = false, features = ["std"] }

[build-dependencies]
napi-build = "2.5.0"

[dev-dependencies]
qrcodegen = "1.8.0"
